#!/bin/bash

# Figure out the file path
if [[ -z "${JOURNAL}" ]]; then
	todayPath="$HOME/Desktop"
else
	todayPath="${JOURNAL}"
fi
todayFile="$todayPath/$(date +%F)-journal.gmi"
new=0

# Check if the file exists
if [ ! -f "$todayFile" ]; then
	# Create it if needed
	if [ ! "$#" -eq 0 ]; then
		touch "$todayFile"
		new=1
	else
		echo "No journal yet today"
		exit
	fi
fi

# If there's no input just cat the file
if [ "$#" -eq 0 ]; then
	cat $todayFile
	exit
fi

# If the input is a command, do that
if [ "$1" == "nano" ]; then
	nano $todayFile
	exit
fi

# If the file is new add a title
if [ $new -eq 1 ]; then
	# Make up a title unless the input has one
	if [[ ! "$@" == *"# "* ]]; then
		echo "# $(date +%F) - Journal" >> $todayFile
	fi
fi
echo "$@" >> $todayFile
echo >> $todayFile
echo
echo "Journaled to: $todayFile"
if [ $new -eq 0 ]; then
    tail $todayFile
fi
