#!/bin/bash
if [[ -z "${JOURNAL}" ]]; then
	todayPath="$HOME"
else
	todayPath="${JOURNAL}"
fi
todayFile="$todayPath/$(date +%F)-journal.gmi"
new=0
if [ ! -f "$todayFile" ]; then
    touch "$todayFile"
    new=1
fi
if [ "$#" -eq 0 ]; then
    cat $todayFile
    exit
fi
echo "$@" >> $todayFile
echo
echo "Journaled to: $todayFile"
if [ $new -eq 0 ]; then
    cat $todayFile
fi
