#!/bin/bash
curl icanhazip.com
#curl api.ipify.org
exit
nslookup myip.opendns.com resolver1.opendns.com
if [ "$1" = "-c" ]; then
	type xclip >/dev/null 2>&1 || { echo >&2 "xclip not found."; exit 1; }
	LOOK_FOR=Address:
	FOUND=`nslookup myip.opendns.com resolver1.opendns.com | grep ^$LOOK_FOR | tail -1`
	arrIN=(${FOUND// / })
	echo -n ${arrIN[1]} | xclip -sel clip
fi
